name: Dev CI

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install upx
        run: sudo apt-get install -y upx-ucl

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test -- --nocapture

      - name: Test (encryption)
        run: cargo test --features encryption -- --nocapture

      - name: Test (mcp + encryption)
        run: cargo test --features "mcp encryption" -- --nocapture
